# This is a development enviorment please dont use in prod :pray:


version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"

    environment:
      - FLASK_ENV=development
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-hackdb}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy # Wait for the db healthcheck to pass
      redis:
        condition: service_started
    networks:
      - app-network
    env_file:
      - ./.env

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-hackdb} 
    ports:
      - "5432:5432"
    healthcheck: # this needs healthcheck because else the backend will crash lol
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-user} -d $${POSTGRES_DB:-hackdb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge


