apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackdb-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackdb-db
  template:
    metadata:
      labels:
        app: hackdb-db
    spec:
      containers:
      - name: hackdb-db
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "hackdb"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: hackdb-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: hackdb-db