apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackdb-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: hackdb.hexagonical.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hackdb-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hackdb-backend
            port:
              number: 5000