apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackdb-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackdb-backend
  template:
    metadata:
      labels:
        app: hackdb-backend
    spec:
      containers:
      - name: hackdb-backend
        image: ghcr.io/meepstertron/hackdb-backend:latest
        envFrom:
        - secretRef:
            name: backend-secret
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hackdb-backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: hackdb-backend