name: Build and Deploy
permissions: write-all
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ghcr.io/meepstertron/hackdb-frontend:latest
    

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ghcr.io/meepstertron/hackdb-backend:latest

    - name: Set up Kubeconfig
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo -n "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config
        chmod 600 ~/.kube/config
        kubectl config use-context github-deployer-context

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-deployment-db.yaml
        kubectl apply -f k8s-deployment-backend.yaml
        kubectl apply -f k8s-deployment-frontend.yaml
        kubectl apply -f k8s-deployment-worker.yaml
        kubectl apply -f k8s-deployment-redis.yaml
        kubectl apply -f k8s-ingress.yaml
        kubectl apply -f k8s-pvc.yaml


    - name: Roll out deployments
      run: |
        kubectl rollout restart deployment/hackdb-frontend
        kubectl rollout restart deployment/hackdb-backend
        kubectl rollout restart deployment/hackdb-worker
        kubectl rollout restart deployment/hackdb-redis

    - name: Commit docs to repo
      uses: actions/checkout@v4
      with:
        repository: hexagonicalhq/docs
        token: ${{ secrets.PAT_HEXAGONICALHQ }}
        path: docs-repo

    - name: Copy docs to target repo
      run: |
        mkdir -p docs-repo/hackdb
        cp -r ./docs/* docs-repo/hackdb/
        mv docs-repo/hackdb/index.md docs-repo/hackdb.md

    - name: Commit and push changes
      run: |
        cd docs-repo
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Add HackDB docs"
        git push